# Generated by Django 4.2.1 on 2023-06-04 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
       migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=319, null=True, unique=True)),
                ('login', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('User', 'User'), ('Breeder', 'Breeder'), ('Manager', 'Manager'), ('Admin', 'Admin')], max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('number', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('parent1', models.CharField(max_length=64, null=True)),
                ('parent2', models.CharField(max_length=64, null=True)),
                ('gender',
                 models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=9)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.bird')),
                ('user_former', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=128)),
                ('flat', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
